version: "3.9"

networks:
  tweet_network:
    driver: bridge

services:
  db:
    container_name: tweet_db_skillbox
    image: postgres
    mem_limit: 1GB
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tweet_api
    networks:
      - tweet_network

  tweet_api:
    container_name: tweet_api_skillbox
    mem_limit: 1GB
    build: ./src
    ports:
      - "8000:8000"
    networks:
      - tweet_network

  frontend:
    mem_limit: 1GB
    build:
      context: ./front
    ports:
      - "8080:80"
    depends_on:
      - tweet_api
    networks:
      - tweet_network

  test_api:
    container_name: test_api_skillbox
    mem_limit: 1GB
    build: ./tests
    command: ["sh", "-c", "pytest && exit 0"]
    depends_on:
      - tweet_api
    networks:
      - tweet_network
